SOLUTION_NAME = Koturn.Windows.Inputs
SOLUTION_FILE = $(SOLUTION_NAME).sln
MAIN_PROJECT_FILE = $(SOLUTION_NAME)\$(SOLUTION_NAME).csproj
PROJECT_OUTPUTS = $(SOLUTION_NAME)\bin $(SOLUTION_NAME)\obj
ARTIFACTS_BASEDIR = Artifacts
ARTIFACTS_SUBDIR_BASENAME = $(SOLUTION_NAME)
ARTIFACTS_BASENAME = $(SOLUTION_NAME)
BUILD_CONFIG = Release
BUILD_PLATFORM = "Any CPU"
TARGET_NETSTD20 = netstandard2.0-windows
TARGET_NET8 = net8.0-windows
TARGET_NET9 = net9.0-windows
RM = del /F /Q


all: build

build:
	dotnet restore -p:Platform=$(BUILD_PLATFORM) $(SOLUTION_FILE)
	dotnet build -c $(BUILD_CONFIG) -p:Platform=$(BUILD_PLATFORM) $(SOLUTION_FILE)

deploy: deploy-$(TARGET_NETSTD20) deploy-$(TARGET_NET8) deploy-$(TARGET_NET9)

deploy-$(TARGET_NETSTD20):
	dotnet publish --nologo -c $(BUILD_CONFIG) -p:PublishAot=false -p:TargetFramework=$(TARGET_NETSTD20) -o $(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NETSTD20) $(PROJECT_FILE)
	$(RM) $(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NETSTD20)\*.pdb
	$(RM) $(ARTIFACTS_BASENAME)-$(TARGET_NETSTD20).zip 2>NUL
	set OLDCD=$(CD)
	cd $(ARTIFACTS_BASEDIR)
	powershell Compress-Archive -Path $(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NETSTD20) -DestinationPath ..\$(ARTIFACTS_BASENAME)-$(TARGET_NETSTD20).zip
	cd $(OLDCD)

deploy-$(TARGET_NET8):
	dotnet publish --nologo -c $(BUILD_CONFIG) -p:PublishAot=false -p:TargetFramework=$(TARGET_NET8) -o $(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET8) $(PROJECT_FILE)
	$(RM) $(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET8)\*.pdb
	$(RM) $(ARTIFACTS_BASENAME)-$(TARGET_NET8).zip 2>NUL
	set OLDCD=$(CD)
	cd $(ARTIFACTS_BASEDIR)
	powershell Compress-Archive -Path $(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET8) -DestinationPath ..\$(ARTIFACTS_BASENAME)-$(TARGET_NET8).zip
	cd $(OLDCD)

deploy-$(TARGET_NET9):
	dotnet publish --nologo -c $(BUILD_CONFIG) -p:PublishAot=false -p:TargetFramework=$(TARGET_NET9) -o $(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9) $(PROJECT_FILE)
	$(RM) $(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)\*.pdb
	$(RM) $(ARTIFACTS_BASENAME)-$(TARGET_NET9).zip 2>NUL
	set OLDCD=$(CD)
	cd $(ARTIFACTS_BASEDIR)
	powershell Compress-Archive -Path $(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9) -DestinationPath ..\$(ARTIFACTS_BASENAME)-$(TARGET_NET9).zip
	cd $(OLDCD)

clean:
	$(RM) $(PROJECT_OUTPUTS)

distclean:
	$(RM) $(PROJECT_OUTPUTS) $(ARTIFACTS_BASEDIR) $(ARTIFACTS_BASENAME)-*.zip 2>NUL
