using System.Runtime.InteropServices;


namespace Koturn.Windows.Inputs
{
    /// <summary>
    /// Contains information about a simulated message generated by an input device other than a keyboard or mouse.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct HardwareInput
    {
        /// <summary>
        /// The message generated by the input hardware.
        /// </summary>
        public int Message { get; set; }
        /// <summary>
        /// The low-order word of the lParam parameter for <see cref="Message"/>.
        /// </summary>
        public short ParamL { get; set; }
        /// <summary>
        /// The high-order word of the lParam parameter for <see cref="Message"/>.
        /// </summary>
        public short ParamH { get; set; }


        /// <summary>
        /// Initialize all members.
        /// </summary>
        /// <param name="message">The message generated by the input hardware.</param>
        /// <param name="paramL">The low-order word of the lParam parameter for <see cref="Message"/>.</param>
        /// <param name="paramH">The high-order word of the lParam parameter for <see cref="Message"/>.</param>
        public HardwareInput(int message, short paramL, short paramH)
        {
            Message = message;
            ParamL = paramL;
            ParamH = paramH;
        }
    }
}
